name: spinnaker image sync

env:
  SPINNAKER_VERSION: 1.27.0
  HALYARD_IMAGE_ADDRESS: us-docker.pkg.dev/spinnaker-community/docker/halyard:stable
  SPINNAKER_IMAGES_URL: "us-docker.pkg.dev/spinnaker-community/docker/"
  DOCKERHUB_URL: docker.io/dsxphdh01/halyard:stable
  TAG_FILE: "tagfile.txt"
  BOM_DIR: ".boms"

on:
  push:
    paths:
      - '.github/workflows/image_sync.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: run halyard and get bom
        run: |
          docker run -itd -p 8084:8084 -p 9000:9000 --name halyard  us-docker.pkg.dev/spinnaker-community/docker/halyard:stable
          sleep 3
          docker cp scripts/getbomconfig.sh halyard:/opt/getbomconfig.sh
          docker exec -u root halyard chmod +x /opt/getbomconfig.sh
          docker exec -u root halyard sh /opt/getbomconfig.sh ${SPINNAKER_VERSION}
          docker cp halyard:/opt/${SPINNAKER_VERSION}.yml ./${SPINNAKER_VERSION}.yml
          cat ${SPINNAKER_VERSION}.yml


      - name: get bom version file
        run: |
          python3 scripts/bomversion.py ${SPINNAKER_VERSION}.yml  ${TAG_FILE} ${BOM_DIR}
          cat ${TAG_FILE}